package com.java.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.dep_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private String depName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.id
     *
     * @return the value of t_department.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.id
     *
     * @param id the value for t_department.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.dep_name
     *
     * @return the value of t_department.dep_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.dep_name
     *
     * @param depName the value for t_department.dep_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }
}