package com.java.bean;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_x.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_x.last_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_x.gender
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_x.email
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_x.dep_id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    private Integer depId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_x.id
     *
     * @return the value of t_employee_x.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_x.id
     *
     * @param id the value for t_employee_x.id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_x.last_name
     *
     * @return the value of t_employee_x.last_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_x.last_name
     *
     * @param lastName the value for t_employee_x.last_name
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_x.gender
     *
     * @return the value of t_employee_x.gender
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_x.gender
     *
     * @param gender the value for t_employee_x.gender
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_x.email
     *
     * @return the value of t_employee_x.email
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_x.email
     *
     * @param email the value for t_employee_x.email
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_x.dep_id
     *
     * @return the value of t_employee_x.dep_id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_x.dep_id
     *
     * @param depId the value for t_employee_x.dep_id
     *
     * @mbg.generated Tue Sep 22 15:11:33 CST 2020
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }
}